/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import modelo.Ingrediente;
import modelo.Pizza;
import modelo.Pizzaria;

/**
 * Classe JFrame que será a tela principal do sistema de gestão da Pizzaria
 * @author Vitor
 */
public class MenuPrincipalUI extends javax.swing.JFrame {
    
    private Pizzaria pizzaria;
    /**
     * Creates new form Janela
     */
    public MenuPrincipalUI() {
        initComponents();
        pizzaria = new Pizzaria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_novopedido = new javax.swing.JButton();
        btn_resumodia = new javax.swing.JButton();
        btn_estoqueingredientes = new javax.swing.JButton();
        btn_cabana = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Freddy Fazbear Pizzaria");
        setPreferredSize(new java.awt.Dimension(757, 757));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Bem vindo ao Sistema de Gestão da");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Freddy Fazbear Pizzaria");

        btn_novopedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_novopedido.setText("Fazer Novo Pedido");
        btn_novopedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novopedidoActionPerformed(evt);
            }
        });

        btn_resumodia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_resumodia.setText("Ver resumo do dia");
        btn_resumodia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resumodiaActionPerformed(evt);
            }
        });

        btn_estoqueingredientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_estoqueingredientes.setText("Ver estoque de ingredientes");
        btn_estoqueingredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estoqueingredientesActionPerformed(evt);
            }
        });

        btn_cabana.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cabana.setText("Ir pro cabana");
        btn_cabana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cabanaActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/freddy_fazbear_pizza_logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 181, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_novopedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_estoqueingredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_resumodia, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(btn_cabana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(262, 262, 262))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_novopedido)
                    .addComponent(btn_resumodia))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_estoqueingredientes)
                    .addComponent(btn_cabana))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cabanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cabanaActionPerformed

    }//GEN-LAST:event_btn_cabanaActionPerformed

    private void btn_novopedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novopedidoActionPerformed

        new NovoPedidoUI(pizzaria).setVisible(true);
    }//GEN-LAST:event_btn_novopedidoActionPerformed

    private void btn_estoqueingredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estoqueingredientesActionPerformed

        new EstoqueIngredientesUI(pizzaria).setVisible(true);
    }//GEN-LAST:event_btn_estoqueingredientesActionPerformed

    private void btn_resumodiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resumodiaActionPerformed
        new ResumoDiaUI(pizzaria).setVisible(true);
    }//GEN-LAST:event_btn_resumodiaActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
    public static void main(String args[]) {
        // Usar separadores de caminho independentes de sistema operacional
        String filepath = "src" + File.separator + "sounds" + File.separator + "fnaf_music.wav";
        PlayMusic(filepath);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalUI().setVisible(true);
            }
        });
    }
 
    public static void PlayMusic(String location){
        try{
            // Tentar vários caminhos possíveis
            File musicPath = new File(location);
            if (!musicPath.exists()) {
                // Tentar com caminho absoluto do projeto
                String projectPath = System.getProperty("user.dir");
                musicPath = new File(projectPath + File.separator + location);
                
                // Se ainda não encontrou, tente outras alternativas
                if (!musicPath.exists()) {
                    String[] possiveisCaminhos = {
                        "ProjetoFinal" + File.separator + location,
                        ".." + File.separator + location
                    };
                    
                    for (String caminho : possiveisCaminhos) {
                        File tentativa = new File(caminho);
                        if (tentativa.exists()) {
                            musicPath = tentativa;
                            break;
                        }
                    }
                }
            }
            
            if(musicPath.exists()){
                System.out.println("Arquivo de música encontrado: " + musicPath.getAbsolutePath());
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                Clip clip = AudioSystem.getClip();
                clip.open(audioInput);
                
                // Controle de volume - valores negativos diminuem o volume
                // -10.0f volume moderadamente baixo
                // -20.0f volume baixo
                // -30.of volume beeeem baixinho
                if (clip.isControlSupported(javax.sound.sampled.FloatControl.Type.MASTER_GAIN)) {
                    javax.sound.sampled.FloatControl gainControl = 
                        (javax.sound.sampled.FloatControl) clip.getControl(
                            javax.sound.sampled.FloatControl.Type.MASTER_GAIN);
                    gainControl.setValue(-20.0f); // Reduz o volume (valores negativos em dB)
                }
                
                clip.start();
                clip.loop(999);
            } else {
                System.err.println("Arquivo de música não encontrado: " + location);
            }
        }
        catch(Exception e){
            System.err.println("Erro ao reproduzir música: " + e.getMessage());
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cabana;
    private javax.swing.JButton btn_estoqueingredientes;
    private javax.swing.JButton btn_novopedido;
    private javax.swing.JButton btn_resumodia;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
