/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import excecoes.EstoqueInsuficienteException;
import modelo.Acompanhamento;
import modelo.Ingrediente;
import modelo.Pedido;
import modelo.Pizza;
import modelo.Pizzaria;

/**
 *
 * @author Vitor
 */
public class NovoPedidoUI extends javax.swing.JFrame {
    
    private Pizzaria pizzaria;
    private Pedido pedido;

    /**
     * Creates new form NovoPedido
     */
    public NovoPedidoUI(Pizzaria pizzaria) {
        initComponents();
        
        this.pizzaria = pizzaria;
        for(int i=0; i<pizzaria.getQuantPizza(); i++)
            tipo_pizza.addItem(pizzaria.getCardapio_pizzas(i).getNome()+" (R$"+pizzaria.getCardapio_pizzas(i).getPreco()+")");
        for(int i=0; i<pizzaria.getQuantBordaPizza(); i++){
            combobox_borda.addItem(pizzaria.getBordaPizza(i).getNome());

        }
        for(int i=0; i<pizzaria.getQuantAcompanhamentos(); i++){
            String aux = pizzaria.getAcompanhamentos(i).getNome()+" (R$"+ pizzaria.getAcompanhamentos(i).getPreco()+")";
            combobox_acomp1.addItem(aux);
            combobox_acomp2.addItem(aux);
            combobox_acomp3.addItem(aux);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nome_cliente = new javax.swing.JTextField();
        tipo_pizza = new javax.swing.JComboBox<>();
        checkbox_acomp = new javax.swing.JCheckBox();
        combobox_acomp1 = new javax.swing.JComboBox<>();
        combobox_acomp2 = new javax.swing.JComboBox<>();
        combobox_acomp3 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        obs = new javax.swing.JTextField();
        btn_concluirpedido = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        checkbox_borda = new javax.swing.JCheckBox();
        combobox_borda = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Novo Pedido");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Novo Pedido");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome do cliente");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tipo de Pizza");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Acompanhamento");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Acompanhamento 1");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Acompanhamento 2");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Acompanhamento 3");

        nome_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_clienteActionPerformed(evt);
            }
        });

        checkbox_acomp.setText("Sim");
        checkbox_acomp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkbox_acompStateChanged(evt);
            }
        });
        checkbox_acomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_acompActionPerformed(evt);
            }
        });

        combobox_acomp1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum" }));
        combobox_acomp1.setEnabled(false);

        combobox_acomp2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum" }));
        combobox_acomp2.setEnabled(false);

        combobox_acomp3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum" }));
        combobox_acomp3.setEnabled(false);
        combobox_acomp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_acomp3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Observações:");

        btn_concluirpedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_concluirpedido.setText("Concluir Pedido");
        btn_concluirpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_concluirpedidoActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Borda Recheada");

        checkbox_borda.setText("Sim (Preço padrão de R$ 10,00)");
        checkbox_borda.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkbox_bordaStateChanged(evt);
            }
        });

        combobox_borda.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Tipo de Borda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combobox_borda, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(combobox_acomp2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(combobox_acomp3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(combobox_acomp1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(59, 59, 59)
                                        .addComponent(obs, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(btn_concluirpedido)
                                        .addGap(108, 108, 108)
                                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(27, 27, 27))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(42, 42, 42)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkbox_borda)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tipo_pizza, 0, 381, Short.MAX_VALUE)
                                            .addComponent(nome_cliente))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(28, 28, 28)
                                    .addComponent(checkbox_acomp)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tipo_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(checkbox_borda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox_borda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(checkbox_acomp))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(combobox_acomp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(combobox_acomp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(combobox_acomp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(obs, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_concluirpedido)
                    .addComponent(btn_cancelar))
                .addGap(30, 30, 30))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {checkbox_acomp, checkbox_borda});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nome_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_clienteActionPerformed

    private void checkbox_acompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_acompActionPerformed
        
    }//GEN-LAST:event_checkbox_acompActionPerformed

    private void btn_concluirpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_concluirpedidoActionPerformed
        Pedido pedido = new Pedido();
        String nome = nome_cliente.getText();
        Pizza pizza = pizzaria.getCardapio_pizzas(tipo_pizza.getSelectedIndex());
        Acompanhamento acomp1 = null;
        Acompanhamento acomp2 = null;
        Acompanhamento acomp3 = null;
        
        if(checkbox_borda.isSelected()){
           pizza.getBorda().setNome(combobox_borda.getItemAt(combobox_borda.getSelectedIndex()));
        }
        
        for(int i=0; i<pizza.getQuantIngredientes(); i++){
            
            try{
                Ingrediente ing = pizza.getIngrediente(i);
                pizzaria.getEstoque().pegarIngrediente(ing);
            }
            catch(EstoqueInsuficienteException ex){
                int aux = i-1;
                javax.swing.JOptionPane.showMessageDialog(
                    null, 
                    ex.getMessage(), 
                    "Erro", 
                    javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }
            //FAZER O MESMO PRA BORDA
        }
        
        if(checkbox_acomp.isSelected()){
            acomp1 = pizzaria.getAcompanhamentos(combobox_acomp1.getSelectedIndex()-1);
            acomp2 = pizzaria.getAcompanhamentos(combobox_acomp2.getSelectedIndex()-1);
            acomp3 = pizzaria.getAcompanhamentos(combobox_acomp3.getSelectedIndex()-1);
        }
        pedido.fazerPedido(nome, pizza, acomp1, acomp2, acomp3, obs.getText());
        pizzaria.adicionarPedidoAoHistorico(pedido);
        javax.swing.JOptionPane.showMessageDialog(
            null, 
            "Pedido feito com sucesso!\nO Pedido deu um valor de R$"+pedido.getValorTotal(), 
            "Pedido completo", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
            
    }//GEN-LAST:event_btn_concluirpedidoActionPerformed

    private void checkbox_acompStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkbox_acompStateChanged
        if(checkbox_acomp.isSelected()){
            combobox_acomp1.setEnabled(true);
            combobox_acomp2.setEnabled(true);
            combobox_acomp3.setEnabled(true);
        }
        else{
            combobox_acomp1.setEnabled(false);
            combobox_acomp2.setEnabled(false);
            combobox_acomp3.setEnabled(false);
        }
    }//GEN-LAST:event_checkbox_acompStateChanged

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void checkbox_bordaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkbox_bordaStateChanged
        if(checkbox_borda.isSelected()){
            combobox_borda.setEnabled(true);

        }
        else{
            combobox_borda.setEnabled(false);
        }
    }//GEN-LAST:event_checkbox_bordaStateChanged

    private void combobox_acomp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_acomp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_acomp3ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_concluirpedido;
    private javax.swing.JCheckBox checkbox_acomp;
    private javax.swing.JCheckBox checkbox_borda;
    private javax.swing.JComboBox<String> combobox_acomp1;
    private javax.swing.JComboBox<String> combobox_acomp2;
    private javax.swing.JComboBox<String> combobox_acomp3;
    private javax.swing.JComboBox<String> combobox_borda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nome_cliente;
    private javax.swing.JTextField obs;
    private javax.swing.JComboBox<String> tipo_pizza;
    // End of variables declaration//GEN-END:variables
}
